include ':app', ':automator', ':common', ':cca', ':inrt'
include ':cca-aar:libtermexec'
include ':cca-aar:emulatorview'
include ':cca-aar:term'
include ':cca-aar:opencv'
include ':js-supports:cca-tool-color-center'
include ':js-supports:cca-tool-download'
include ':js-supports:cca-tool-webview'
include ':js-supports:cca-tool-encrypt'
include ':js-supports:cca-tool-common'
include ':js-supports:native-lib'
include ':cca-aar:rhino-jdk7'
include ':cca-aar:paddleocr'
include ':cca-aar:apksigner'
include ':apkbuilder'
include ':cca-aar:yolov8ncnn'
include ':cca-aar:opencvhelper'
include ':cca-aar:rootshell'
