plugins {
    id 'com.android.library'
}

android {
    namespace 'org.cca.opencvhelper'
    compileSdk 34

    defaultConfig {
        minSdk 21
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(path: ':cca-aar:opencv')
}